name: Sync with upstream

on:
  schedule:
    - cron: '0 0 * * *'  # 每天凌晨0点执行（UTC时间）
  workflow_dispatch:     # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 仓库
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 拉取完整历史

      - name: 设置 Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: 添加上游仓库
        run: |
          git remote add upstream https://github.com/rustdesk/rustdesk.git || true
          git fetch upstream

      - name: 合并上游更新
        run: |
          git checkout master  # 切换到你的主分支（根据实际情况修改）
          git merge upstream/master  # 合并上游的主分支（根据实际情况修改）
          git push origin master  # 推送到你的仓库
